test(workflows): test cd pipeline ...

diff --git a/.github/workflows/dev-cd.yaml b/.github/workflows/dev-cd.yaml
--- a/.github/workflows/dev-cd.yaml
+++ b/.github/workflows/dev-cd.yaml
@@ -70,21 +70,48 @@ jobs:
     needs: [detect, prepare, build-and-push]
     if: needs.detect.outputs.services != '[]' && needs.detect.outputs.services != ''
     runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: manifests
     steps:
       - name: Checkout Manifest
         uses: actions/checkout@v4
         with:
           repository: applyhub7/applyhub-manifests
+          ref: main
           token: ${{ secrets.MANIFEST_REPO_TOKEN }}
           path: manifests
 
-      - name: Update Manifests Repo
+      - name: Configure GitHub Actions Bot
+        run: |
+          git config user.name "github-actions[bot]"
+          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
+
+      - name: Update Image Tag
         env:
           SERVICES: ${{ needs.detect.outputs.services }}
           NEW_TAG: ${{ needs.prepare.outputs.tag }}
         run: |
-          cd manifests
           for changed_service in $(echo "$SERVICES" | jq -r '.[]'); do
             FILE="apps-manifests/env/dev/${changed_service}.yaml"
+            
+            if [[ ! -f "$FILE" ]]; then
+              echo "Manifest file not found: $FILE"
+              exit 1
+            fi
+
             sed -i -E "s/^([[:space:]]*tag:[[:space:]]*).*/\1\"$NEW_TAG\"/" "$FILE"
+            git add "$FILE"
           done
+
+      - name: Push Manifests
+        env:
+          NEW_TAG: ${{ needs.prepare.outputs.tag }}
+        run: |
+          if git diff --cached --quiet; then
+            echo "Nothing changes!"
+            exit 0
+          fi
+
+          git commit -m "deploy(dev): update image tags to $NEW_TAG"
+          git push origin main
